// Ported from microsoft/sqltoolsservice (MIT):
// https://github.com/microsoft/sqltoolsservice/blob/02de444481bccd4492cd4e35e44fb97738f3a770/src/Microsoft.SqlTools.LanguageService/LanguageServices/AutoCompleteHelper.cs
// (AutoCompleteHelper.DefaultCompletionText and IsReservedWord).
//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license.
//
// MIT License
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
// documentation files (the "Software"), to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of
// the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

namespace Mssql.McpServer.LanguageService;

/// <summary>
/// The keyword and built-in list sqltoolsservice offers when the parser has no completions or binding timed out.
/// </summary>
internal static class SqlKeywords
{
    public static readonly string[] DefaultCompletionText =
    [
        "@@error",
        "@@identity",
        "@@rowcount",
        "abort",
        "abs",
        "acos",
        "action",
        "add",
        "all",
        "alter",
        "and",
        "any",
        "apply",
        "approx_count_distinct",
        "approx_percentile_cont",
        "approx_percentile_disc",
        "are",
        "array",
        "as",
        "asc",
        "ascii",
        "asin",
        "at time zone",
        "at",
        "atan",
        "atn2",
        "authorization",
        "auto_drop",
        "auto",
        "avg",
        "backup",
        "begin transaction",
        "begin",
        "between",
        "binary",
        "bit_count",
        "bit",
        "blockers",
        "both",
        "break",
        "bulk",
        "by",
        "call",
        "cascade",
        "case when",
        "case",
        "cast",
        "catalog",
        "catch",
        "ceiling",
        "char",
        "character varying",
        "character",
        "charindex",
        "check",
        "checkpoint",
        "checksum_agg",
        "choose",
        "close",
        "clustered",
        "coalesce",
        "collate",
        "collation",
        "column",
        "columnstore",
        "commit",
        "compress",
        "compute",
        "concat_ws",
        "concat",
        "connect",
        "constraint",
        "constraints",
        "contains",
        "containstable",
        "continue",
        "convert",
        "cos",
        "cot",
        "count_big",
        "count",
        "create",
        "cross join",
        "cross",
        "cte",
        "cume_dist",
        "current date",
        "current timestamp",
        "current user",
        "current_date",
        "current_timestamp",
        "current_user",
        "current",
        "cursor_close_on_commit",
        "cursor_default",
        "cursor",
        "data_compression",
        "data",
        "database",
        "datalength",
        "date_bucket",
        "date",
        "dateadd",
        "datediff",
        "datefromparts",
        "datename",
        "datepart",
        "datetime",
        "datetime2",
        "datetrunc",
        "day",
        "days",
        "db_name",
        "dbcc",
        "deallocate",
        "dec",
        "decimal",
        "declare",
        "decompress",
        "default",
        "degrees",
        "delete",
        "dense_rank",
        "deny",
        "desc",
        "description",
        "difference",
        "disabled",
        "disk",
        "distinct",
        "distributed",
        "double",
        "drop existing",
        "drop_existing",
        "drop",
        "dump",
        "dynamic",
        "else",
        "enable",
        "encrypted",
        "end exec",
        "end-exec",
        "end",
        "escape",
        "except",
        "exec",
        "execute",
        "exists",
        "exit",
        "exp",
        "external",
        "false",
        "fast_forward",
        "fetch",
        "file",
        "filegroup",
        "filename",
        "filestream",
        "fillfactor",
        "filter",
        "first value",
        "first_value",
        "first",
        "float",
        "floor",
        "for",
        "foreign key",
        "foreign",
        "format",
        "formatmessage",
        "freetexttable",
        "from",
        "full join",
        "full",
        "function",
        "generate_series",
        "geography",
        "geometry",
        "get_bit",
        "get",
        "getdate",
        "getutcdate",
        "global",
        "go",
        "goto",
        "grant",
        "group by",
        "group",
        "grouping_id",
        "grouping",
        "hash",
        "hashed",
        "having",
        "hidden",
        "hierarchyid",
        "hierarchyid",
        "holdlock",
        "host_name",
        "hour",
        "hours",
        "ident_current",
        "identity_insert",
        "identity",
        "identitycol",
        "if exists",
        "if",
        "ignore",
        "iif",
        "image",
        "immediate",
        "in",
        "include",
        "index",
        "inner join",
        "inner",
        "input",
        "insensitive",
        "insert",
        "instead",
        "int",
        "integer",
        "intersect",
        "interval",
        "into",
        "is",
        "isdate",
        "isnull",
        "isnumeric",
        "isolation",
        "join",
        "json_modify",
        "json_query",
        "json_value",
        "json",
        "key",
        "lag",
        "language",
        "last value",
        "last_value",
        "last",
        "lead",
        "leading",
        "left join",
        "left_shift",
        "left",
        "len",
        "level",
        "like",
        "lineno",
        "load",
        "local",
        "locate",
        "location",
        "log",
        "log10",
        "login",
        "lower",
        "ltrim",
        "masked",
        "match",
        "max_duration",
        "max",
        "maxdop",
        "merge",
        "message",
        "min",
        "minute",
        "minutes",
        "modify",
        "module",
        "month",
        "move",
        "names",
        "namespace",
        "national",
        "native_compilation",
        "nchar varying",
        "nchar",
        "newid",
        "newsequentialid",
        "next",
        "no",
        "nocheck",
        "nocount",
        "nonclustered",
        "none",
        "norecompute",
        "not null",
        "not",
        "now",
        "ntile",
        "null",
        "nullif",
        "nulls",
        "numeric",
        "nvarchar",
        "object_name",
        "object",
        "of",
        "off",
        "offsets",
        "on",
        "online",
        "only",
        "open",
        "openjson",
        "openquery",
        "openrowset",
        "openxml",
        "option",
        "or",
        "order by",
        "order",
        "out",
        "outer join",
        "outer",
        "output",
        "over",
        "owner",
        "partial",
        "partition by",
        "partition",
        "password",
        "path",
        "patindex",
        "pause",
        "percent_rank",
        "percent",
        "percentage",
        "period",
        "persisted",
        "pi",
        "pivot",
        "plan",
        "policy",
        "position",
        "power",
        "precision",
        "predicate",
        "primary key",
        "primary",
        "print",
        "prior",
        "proc",
        "procedure",
        "public",
        "quarter",
        "query_store",
        "quoted_identifier",
        "quotename",
        "radians",
        "raiserror",
        "rand",
        "range",
        "rank",
        "raw",
        "read only",
        "read write",
        "read_committed_snapshot",
        "read_only",
        "read_write",
        "read",
        "readonly",
        "readtext",
        "real",
        "rebuild",
        "receive",
        "reconfigure",
        "recovery",
        "recursive_triggers",
        "recursive",
        "references",
        "relative",
        "remove",
        "reorganize",
        "replace",
        "replicate",
        "replication",
        "required",
        "respect",
        "restart",
        "restore",
        "restrict",
        "resume",
        "return",
        "returns",
        "reverse",
        "revert",
        "revoke",
        "right join",
        "right_shift",
        "right",
        "rollback",
        "rollup",
        "round",
        "row_number",
        "row",
        "rowcount",
        "rowguidcol",
        "rows",
        "rtrim",
        "rule",
        "sample",
        "save",
        "scalar",
        "schema_name",
        "schema",
        "schemabinding",
        "scope_identity",
        "scoped",
        "scroll",
        "second",
        "secondary",
        "security",
        "select",
        "self",
        "send",
        "sent",
        "sequence",
        "server",
        "session user",
        "session_user",
        "session",
        "sessionproperty",
        "set_bit",
        "set",
        "sets",
        "setuser",
        "shutdown",
        "sign",
        "simple",
        "sin",
        "size",
        "smallint",
        "smallmoney",
        "snapshot",
        "some",
        "soundex",
        "space",
        "sql_variant",
        "sql",
        "sqrt",
        "square",
        "standard",
        "start",
        "started",
        "state",
        "statement",
        "static",
        "statistics_norecompute",
        "statistics",
        "status",
        "stdev",
        "stdevp",
        "stopped",
        "str",
        "string_agg",
        "string_escape",
        "string_split",
        "stuff",
        "substring",
        "sum",
        "suser_name",
        "sysdatetime",
        "sysname",
        "system user",
        "system_time",
        "system_user",
        "system",
        "table",
        "take",
        "tan",
        "target",
        "temporary",
        "then",
        "throw",
        "time",
        "timestamp",
        "tinyint",
        "to",
        "top",
        "trailing",
        "tran",
        "transaction",
        "translate",
        "trigger",
        "trim",
        "true",
        "truncate",
        "try_cast",
        "try_convert",
        "try_parse",
        "try",
        "tsql",
        "type",
        "uncommitted",
        "unicode",
        "union all",
        "union",
        "unique",
        "uniqueidentifier",
        "unknown",
        "unpivot",
        "update",
        "updatetext",
        "upper",
        "use",
        "user_id",
        "user_name",
        "user",
        "using",
        "value",
        "values",
        "var",
        "varchar",
        "varp",
        "varying",
        "version",
        "view",
        "wait_at_low_priority",
        "waitfor",
        "week",
        "when",
        "where",
        "while",
        "with",
        "within",
        "without",
        "work",
        "write",
        "writetext",
        "xact_abort",
        "xml",
        "year",
        "zone",
    ];

    private static readonly HashSet<string> Reserved = new(DefaultCompletionText, StringComparer.OrdinalIgnoreCase);

    /// <summary>True when <paramref name="text"/> is in the keyword list, so an identifier with that name needs brackets.</summary>
    public static bool IsReservedWord(string text) => Reserved.Contains(text);
}
